[package]
name = "nsfw-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
confy = "0.5.1"
hyper = { version = "0.14.24", features = ["full"] }
image = "0.24.5"
reqwest = "0.11.14"
serde = "1.0.152"
serde_derive = "1.0.152"
tokio = { version = "1.26.0", features = ["full"] }
tract-onnx = "0.19.7"
url = "2.3.1"
